# credits: https://github.com/actions-marketplace-validations/desbravacloud_action-create-pull-requests/tree/main
# references: https://docs.github.com/en/rest/pulls/pulls?apiVersion=2022-11-28#create-a-pull-request
#             https://docs.github.com/en/rest/pulls/review-requests?apiVersion=2022-11-28#request-reviewers-for-a-pull-request

name: 'Auto Create Pull Request'
description: 'Automatically Creates Pull Requests'
branding:
  icon: 'git-pull-request'
  color: 'blue'

inputs:
  origin-branch:
    description: 'Origin branch. If blank it will assume the workflow branch.'
    required: false
  target-branch:
    description: 'Target branch'
    required: true
  custom-title:
    description: 'PR title'
    required: false
    default: 'PR created automatically.'
  custom-body:
    description: 'PR body message'
    required: false
  reviewers:
    description: 'PR reviewers'
    required: false
  maintainer_can_modify:
    description: 'Indicates whether maintainers can modify the pull_request.'
    required: false

runs:
  using: "composite"
  steps:
    - run: |
        if [ -z "${{ inputs.origin-branch }}" ]; then
          echo "branch_name=${{ github.ref_name }}" >> $GITHUB_ENV
        else
          echo "branch_name=${{ inputs.origin-branch }}" >> $GITHUB_ENV
        fi
        source $GITHUB_ENV
        echo "Use $branch_name branch"
      shell: bash
    - run: |
        curl -o check_pull_head_branch \
        --url https://api.github.com/repos/${{ github.repository }}/pulls \
        --header "authorization: Bearer ${{ github.token }}" \
        --header "content-type: application/json"
        echo "pull_head_branch=$(cat check_pull_head_branch | jq -r '.[].head | select (.ref == "${{ github.ref_name }}")|.ref')" >> $GITHUB_ENV
      shell: bash
    - run: |
        if [ -z "${{ env.pull_head_branch }}" ]; then
          output=$(echo curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/pulls \
          --header 'authorization: Bearer ${{ github.token }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "${{ inputs.custom-title }} ${{ inputs.target-branch }} < ${{ env.branch_name }}",
            "body": "${{ inputs.custom-body }}",
            "head": "${{ env.branch_name }}",
            "base": "${{ inputs.target-branch }}",
            "maintainer_can_modify": "${{ inputs.maintainer_can_modify }}",
          }')
          echo "$output"
          pr_number="$(jq '.number' <<< "$output")"
          echo "$pr_number"
          curl --request POST \
          --url "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number/requested_reviewers" \
          --header 'authorization: Bearer ${{ github.token }}' \
          --header 'content-type: application/json' \
          --data '{
            "reviewers": $(jq -ncR '[inputs]' <<< "${{ inputs.reviewers }}")
            }' \
          --fail
        
          echo 'Pull request has been created!!!'
        else
          echo 'There is already a Pull Request created from branch ${{ env.branch_name }} to branch ${{ inputs.target-branch }}'
        fi
      shell: bash