name: Update python-requirements.txt file

on:
  push:
    branches: [ master, develop ]
    paths:
      - "pyproject.toml"
      - "poetry.lock"
  workflow_dispatch:
    branches:
      - master
      - develop

jobs:
  update:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python_version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.5.1
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Export python-requirements.txt
        run: poetry export --with dev --format requirements.txt --output .github/python-requirements.txt

      - name: Commit changes if any
        run: |
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git pull -f
            git add .github/python-requirements.txt
            git commit -m "ci: Update python-requirements.txt"
            git push
          fi