name: Update python-requirements.txt file

on:
  push:
    branches:
      - master
      - develop
    paths:
      - "pyproject.toml"
      - "poetry.lock"
  workflow_dispatch:
    branches:
      - master
      - develop

# discard previous execution if you commit to a branch that is already running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    uses: ./.github/workflows/_python.yml
    secrets: inherit
    with:
      working_directory: .
      check_requirements_licenses: false
      requirements_path: ./.github/python-requirements.txt
      packages_path: ./.github/apt-packages.txt
      custom_command: poetry export --format requirements.txt --output ./.github/python-requirements.txt
      python_versions: >-
        [ "3.10"]
      max_timeout: 5
      ubuntu_version: 22.04

  commit-changes:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2
      - name: Commit changes if any
        run: |
          if output=$(git status --porcelain) && [ ! -z "$output" ]; then
            git pull -f
            git commit -m "ci: Update ./.github/python-requirements.txt" -a
            git push
          fi
