name: 'Upstream Sync'

on:
  schedule:
    - cron: '0 9 1 1-12/2 *'
    # https://crontab.guru/#0_9_1_1-12/2_*

  workflow_dispatch:  # click the button on Github repo!

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Fetch upstream
        uses: 135e2/sync-upstream-repo@v0.1.5
        with:
          #Git upstream repo
          upstream_repo: https://github.com/kevoreilly/CAPEv2.git
          upstream_branch: master
          local_branch: upstream
          github_token: ${{ secrets.GITHUB_TOKEN }}
