name: Upstream pull request

on:
#  schedule:
#    - cron: '0 9 1 1-12/2 *' # https://crontab.guru/#0_9_1_1-12/2_*
  workflow_dispatch:
    inputs: {}

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create upstream branch
        run: |
             git remote add upstream https://github.com/kevoreilly/CAPEv2.git
             git fetch upstream
             git branch upstream-master upstream/master

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Merge with upstream
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          base: develop
          branch: upstream-master
          delete-branch: true
          title: 'Merge with upstream'
          body: |
            Merge with upstream
            - Auto-generated by [create-pull-request][1]

            [1]: https://github.com/peter-evans/create-pull-request
          labels: |
            upstream
            automated pr
          assignees: federicofantini
          reviewers: federicofantini