name: upstream to PR

on:
  schedule:
    - cron: '0 9 1 1-12/2 *' # https://crontab.guru/#0_9_1_1-12/2_*
  workflow_dispatch:
    inputs: {}

jobs:
  autoupdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ignore .github conflicts
        run: echo ".github" > .git/info/exclude

      - uses: fopina/upstream-to-pr@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          upstream-repository: https://github.com/kevoreilly/CAPEv2.git
          upstream-branch: master