name: Upstream pull request

on:
#  schedule:
#    - cron: '0 9 1 1-12/2 *' # https://crontab.guru/#0_9_1_1-12/2_*
  workflow_dispatch:
    inputs: {}

jobs:
  upstream_pull_request:
    runs-on: ubuntu-latest
    name: upstream_pull_request
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: create pull request
        run: |
             git remote add upstream https://github.com/kevoreilly/CAPEv2.git
             git fetch upstream
#             git checkout -b upstream-master upstream/master
             gh pr create -B develop -H upstream/master --title 'Merge upstream-master into develop' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}