name: Upstream pull request

on:
#  schedule:
#    - cron: '0 9 1 1-12/2 *' # https://crontab.guru/#0_9_1_1-12/2_*
  workflow_dispatch:
    inputs: {}

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2

      - name: Create pr from upstream
        run: |
             git remote add upstream https://github.com/kevoreilly/CAPEv2.git
             git remote -v
             git fetch origin
             git fetch upstream
             git checkout -b "upstream-master" upstream/master
             git branch --all
             git rm -r .github
             git push -u origin "upstream-master"

#             git config pull.rebase false
#             git config --list
#             git pull upstream master
#             git push -u origin "upstream-$(date '+%Y-%m-%d')"
#             git remote remove upstream
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Create PR
        uses: desbravacloud/action-create-pull-requests@v1
        with:
          origin-branch: "upstream-master"
          target-branch: 'develop'
          custom-title: 'Merge upstream'
          custom-body: 'Please, check thease changes :)'