name: Upstream pull request

on:
#  schedule:
#    - cron: '0 9 1 1-12/2 *' # https://crontab.guru/#0_9_1_1-12/2_*
  workflow_dispatch:
    inputs: {}

jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create pr from upstream
        run: |
             git fetch origin
             git remote add upstream https://github.com/kevoreilly/CAPEv2.git
             git fetch upstream
             git checkout -b upstream-master upstream/master
             git checkout -b develop origin/develop
             git branch -a
             gh pr create -B develop -H upstream-master --title 'Merge upstream/master into develop' --body 'Created by Github action'
        env:
          GH_TOKEN: ${{ github.token }}
