name: Upstream pull request

on:
  schedule:
    - cron: '0 0 1 * *' # https://crontab.guru/#0_0_1_*_*
  workflow_dispatch:
    branches:
      - master
      - develop

jobs:
  createPullRequestFromUpstream:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: fregante/setup-git-user@v2

      - name: Create upstream master branch
        run: |
             git remote add upstream https://github.com/kevoreilly/CAPEv2.git
             git remote -v
             git fetch origin
             git fetch upstream
             if [[ $(git ls-remote --heads origin refs/heads/upstream-master) == *upstream-master* ]]; then
               echo "Remote branch 'upstream-master' already exists. Maybe there is already a PR?"
               exit 1
             fi
             echo 'git checkout -b "upstream-master" upstream/master'
             git checkout -b "upstream-master" upstream/master
             git branch --all
             rm -rf .github
             git add .github
             echo 'git commit -m "Removed upstream CI"'
             git commit -m "Removed upstream CI"
             git push -u origin upstream-master
        env:
          GH_TOKEN: ${{ github.token }}

      - uses: actions/checkout@v4  # otherwise he can't see the action

      - name: Create PR from upstream
        uses: ./.github/actions/pull_request
        with:
          origin-branch: "upstream-master"
          target-branch: 'develop'
          custom-title: '[AUTO] It is the time to merge'
          custom-body: 'Please, check thease changes and merge it :)'
          reviewers: "federicofantini"
          maintainer_can_modify: true
