name: Upstream pull request

on:
#  schedule:
#    - cron: '0 9 1 1-12/2 *' # https://crontab.guru/#0_9_1_1-12/2_*
  push:
    branches: [ master ]

jobs:
  release_pull_request:
    runs-on: ubuntu-latest
    name: release_pull_request
    steps:
    - name: checkout
      uses: actions/checkout@v1

    - name: Create PR to branch
      uses: gorillio/github-action-sync@master
      with:
        upstream: https://github.com/kevoreilly/CAPEv2
        upstream_branch: master
        branch: develop
        pr_labels: upstream
      env:
        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        GITBOT_EMAIL: yo@gorill.io
        DRY_RUN: false
