name: PIP audit

on:
  schedule:
    - cron: '0 8 * * 1'
  workflow_dispatch:
    branches:
      - master
      - develop

# discard previous execution if you commit to a branch that is already running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-pip-audit:
    uses: ./.github/workflows/_python.yml
    secrets: inherit
    with:
      working_directory: .
      requirements_path: ./.github/python-requirements.txt
      packages_path: ./.github/apt-packages.txt
      custom_command: pip-audit -r ./.github/python-requirements.txt
      python_versions: >-
        [ "3.10"]
      max_timeout: 5
      ubuntu_version: 22.04
