name: CI

on:
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:
    branches:
      - master
      - develop

# discard previous execution if you commit to a branch that is already running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-all-tests:
    uses: ./.github/workflows/_python.yml
    secrets: inherit
    with:
      working_directory: .
      check_requirements_licenses: false
      use_black: false
      use_isort: false
      use_flake8: false
      use_pylint: false
      use_bandit: false
      use_autoflake: false
      django_settings_module: web.settings
      # no docker build for the moment -> 1 build is about 20 minutes!
      use_postgres: false
      use_memcached: false
      use_elastic_search: false
      use_rabbitmq: false
      use_mongo: false
      use_celery: false
      use_coverage: true
      upload_coverage: true
      requirements_path: .github/python-requirements.txt
      packages_path: ./.github/apt-packages.txt
      # - malwareconfig had a broken dep with pycrypto==2.6.1 -> installing it only for the tests.
      # - pyattck 7.X.X conflicts with certego-saas, we can only install the version 6.0.0 in the poetry project -> installing it only for the tests.
      # - /usr/bin/unrar binary path is broken with cached package -> installing again every time
      custom_commands: |
        pwd
        python utils/community.py -waf -cr --mitre-offline
        pip install --no-deps malwareconfig
        pip install pyattck
        sudo apt install -y unrar
        pytest -c web/pytest.ini --ds="web.settings" --import-mode=append
        pytest -c web/pytest.ini --ds="web.settings" tests_parsers -s --import-mode=append
        ruff . --line-length 132 --ignore E501,E402,E722
      env: >-
        {"ENV": "ci", "DJANGO_SETTINGS_MODULE": "web.settings"}
      python_versions: >-
        ["3.10"]
      max_timeout: 8
      ubuntu_version: 22.04
