name: CI

on:
  pull_request:
    branches:
      - master
      - develop

# discard previous execution if you commit to a branch that is already running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  detect-changes:
    uses: ./.github/workflows/_detect_changes.yml
    with:
      backend_directories: .github
      frontend_directories: .github
      ubuntu_version: latest

  python:
     needs: detect-changes
     if: ${{ needs.detect-changes.outputs.backend > 0 }}
     uses: ./.github/workflows/_python.yml
     secrets: inherit
     with:
      working_directory: .
      use_black: true
      use_isort: true
      requirements_path: ./.github/python-requirements.txt
      packages_path: ./.github/apt-packages.txt
      django_settings_module: web.settings
      # no docker build for the moment -> 1 build is about 20 minutes!
      use_postgres: false
      use_memcached: false
      use_elastic_search: false
      use_rabbitmq: false
      use_mongo: false
      use_celery: false
      use_coverage: true
      upload_coverage: true
      tags_for_slow_tests: main
      tags_for_manual_tests: manual
      python_versions: >-
        [ "3.10"]
      max_timeout: 5
      ubuntu_version: 20.04
