name: Python package

env:
  COLUMNS: 120

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:
    branches:
      - master
      - develop

# discard previous execution if you commit to a branch that is already running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-all-tests:
    uses: ./.github/workflows/_python.yml
    secrets: inherit
    with:
      working_directory: .
      check_requirements_licenses: false
      requirements_path: .github/python-requirements.txt
      packages_path: ./.github/apt-packages.txt
      custom_commands: |
                      python utils/community.py -waf -cr
                      python web/manage.py makemigrations
                      python web/manage.py migrate
                      pytest --import-mode=append
                      pytest tests_parsers -s --import-mode=append
                      ruff . --line-length 132 --ignore E501,E402
      env: >-
        {"ENV": "ci"}
      python_versions: >-
        [ "3.10"]
      max_timeout: 8
      ubuntu_version: 22.04
