name: Python package

env:
  COLUMNS: 120

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches:
      - master
      - develop

# discard previous execution if you commit to a branch that is already running
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  setup:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Creating CAPEv2 log folders
        run: |
           sudo mkdir -p /var/log/capybox/django /var/log/capybox/web /var/log/capybox/rooter /var/log/capybox/processor \
           && sudo chmod -R 777 /var/log/capybox/django /var/log/capybox/web /var/log/capybox/rooter /var/log/capybox/processor

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout test files repo
        uses: actions/checkout@v4
        with:
          repository: CAPESandbox/CAPE-TestFiles
          path: tests/data/

  run-all-tests:
    needs: setup
    uses: ./.github/workflows/_python.yml
    secrets: inherit
    with:
      working_directory: .
      check_requirements_licenses: false
      requirements_path: .github/python-requirements.txt
      packages_path: ./.github/apt-packages.txt
      custom_command: |
                      python utils/community.py -waf -cr; \
                      python -m pytest --import-mode=append; \
                      python -m pytest tests_parsers -s --import-mode=append; \
                      ruff . --line-length 132 --ignore E501,E402
      env: >-
        {"ENV": "ci"}
      python_versions: >-
        [ "3.10"]
      max_timeout: 5
      ubuntu_version: 22.04
